image: maven:3.9-eclipse-temurin-21-alpine

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

run-tests:
  stage: test
  script:
    - mvn clean test
    - cd backend