spring:
  application:
    name: midi-generator
  datasource:
    url: jdbc:postgresql://localhost:5432/midi_generator
    username: postgres
    password: "0242"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update